# Site Settings
title: Mitchell Duncan
email: twosixmitch@gmail.com
description: Mitchell Duncan's website and blog
baseurl: ""
url: "https://twosixmitch.github.io"
twitter_username: twosixmitch
github_username:  twosixmitch
# Build Settings
plugins:
  - jekyll-sitemap
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"